---
title: "Intro to R Workshop"
toc: false
execute: 
  freeze: auto
---

Hey there!

This is the welcome page for the **Kansas State University 2019 AGSA R Workshop - Introduction to R**, taught by [leombastos](https://github.com/leombastos).

The workshop was divided into 2 days, 2 hours per day:

-   **day 1**:
    -   Basics (1h)
        -   R and RStudio (RStudio panels).
        -   R role in reproducible research.
        -   R basic concepts (package, function, argument, object, object classes).
        -   Creating a data set.
        -   Checking data (summary, glimpse).
        -   Intro to ggplot (philosophy).
        -   Using ggplot for exploratory data viz.
    -   Intermediate (1h)
        -   Using RStudio projects.\
        -   Import data, discuss about tidy data concept.\
        -   Using dplyr and tidyr for data wrangling.\
        -   EXERCISE!
-   **day 2**:
    -   Intermediate (2h)
        -   Run RCBD model, talk about model specification syntax.
        -   Look into ANOVA.
        -   Check model assumptions (talk about assumptions and what to do when they are violated).
        -   Extract model means and pairwise comparison results.
        -   Creating publication-ready plot with means and letters.

## **Interested in "attending" the workshop?**

1.  Go to [this GitHub repository](https://github.com/leombastos/2019_rworkshop_introtoR) and download it to your computer (click on the green "Code" button above and select "*Download ZIP*").

2.  Unzip the repository, launch the RStudio project (by clicking on the "*2019_rworkshop_introtoR.Rproj*" file).

3.  On RStudio, go to the "*Files*" tab (lower right), click on folder "*markdown*", and open file

    -   "*Basic1_partial.R*" for day 1, basics
    -   "*Intermediate1_partial.Rmd*" for day 1, intermediate\
    -   "*Intermediate2_partial.Rmd*" for day 2, intermediate

4.  You can code along with us by watching the following YouTube videos:

    -   [day 1](https://youtu.be/1746LreLYMs)\

        ::: youtube-responsive-container
        <iframe width="560" height="315" src="https://www.youtube.com/embed/1746LreLYMs" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

        </iframe>
        :::

    -   [day 2](https://youtu.be/kaOSJYwJu7I)\

        ::: youtube-responsive-container
        <iframe width="560" height="315" src="https://www.youtube.com/embed/kaOSJYwJu7I" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

        </iframe>
        :::
