---
title: "Data Wrangling and Iteration Workshop"
toc: false
execute: 
  freeze: auto
---

Hey there!

This is the welcome page for the **Kansas State University 2021 AGSA R Workshop - Data wrangling and iteration**, taught on November 16th by [leombastos](https://github.com/leombastos).

The workshop is divided into 2 main sessions (1h/session):

-   Data wrangling using popular functions like
    -   `clean_names()`\
    -   `filter()`\
    -   `mutate()`\
    -   `case_when()`\
    -   `pivot_longer()` and `pivot_wider()`\
    -   `group_by()` and `summarise()`\
    -   `select()`\
    -   the piper operator `%>%`\
-   Iteration using the `map()` and `map2()` functions

## **Interested in "attending" the workshop?**

1.  Go to [this GitHub repository](https://github.com/leombastos/2021_rworkshop_wrangling) and download it to your computer (click on the green "Code" button above and select "*Download ZIP*").

2.  Unzip the repository, launch the RStudio project (by clicking on the "*2021_rworkshop_wrangling.Rproj*" file).

3.  On RStudio, go to the "*Files*" tab (lower right), click on folder "*markdown*", and open file

    -   "*session1_partial.Rmd*" for data wrangling\
    -   "*session2_partial.Rmd*" for iteration

4.  You can code along with us by watching the following YouTube videos:

    -   [wrangling](https://www.youtube.com/watch?v=a1xDkdfrmfc)\

        ::: youtube-responsive-container
        <iframe width="560" height="315" src="https://www.youtube.com/embed/a1xDkdfrmfc" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

        </iframe>
        :::

    -   [iteration](https://www.youtube.com/watch?v=B0OPkdqHkVg)\

        ::: youtube-responsive-container
        <iframe width="560" height="315" src="https://www.youtube.com/embed/B0OPkdqHkVg" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

        </iframe>
        :::
