---
title: "Multivariate Analysis Workshop"
toc: false
execute: 
  freeze: auto
---

Hey there!

This is the welcome page for the **Kansas State University 2021 AGSA R Workshop - Multivariate analysis**, taught on April 7th and 8th 2021 by [leombastos](https://github.com/leombastos) and [adriancorrendo](https://github.com/adriancorrendo).

The workshop was divided into 2 days:

-   **day 1 (Leo Bastos)**:
    -   Understanding multicollinearity\
    -   Principal Component Analysis (dimensionality reduction)
    -   k-means (clustering)
-   **day 2 (Adrian Correndo)**:
    -   Conditional inference tree\
    -   Random forest\
    -   Training/validating/testing predictive models

## **Interested in "attending" the workshop?**

1.  Go to [this GitHub repository](https://github.com/leombastos/2021_rworkshop_mulvitariate) and download it to your computer (click on the green "Code" button above and select "*Download ZIP*").

2.  Unzip the repository, launch the RStudio project (by clicking on the "*2021_rworkshop_multivariate.Rproj*" file).

3.  On RStudio, go to the "*Files*" tab (lower right), click on folder "*markdown*", and open file

    -   "*day1_partial.Rmd*" for day 1\
    -   "*day2_partial.Rmd*" for day 2

4.  You can code along with us by watching the following YouTube videos:

    -   [day 1](https://youtu.be/JsTQctso1nM)\

        ::: youtube-responsive-container
        <iframe width="560" height="315" src="https://www.youtube.com/embed/JsTQctso1nM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

        </iframe>
        :::

    -   [day 2](https://youtu.be/fYv4uxSKp-o)\

        ::: youtube-responsive-container
        <iframe width="560" height="315" src="https://www.youtube.com/embed/fYv4uxSKp-o" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>

        </iframe>
        :::
