---
title: "CRSS 4060/6060\\\nAdvc. Topics in Precision Ag.\\\nBastos Material\\\n(UGA Spring 2022)"
execute: 
  freeze: auto
---

Hi there!

This is the welcome page for the **2022 CRSS 4060/6060 Advanced Topics in Precision Agriculture** portion taught by Dr. Leo Bastos.

------------------------------------------------------------------------

# 1. Overall Learning Objectives `r icons::fontawesome("bullseye")`

The overall learning objectives of my part are:

-   Learn about concepts of spatial data quality control, project management, and reproducibility applied to precision agriculture.

-   Understand the difference between **vector** and **raster** data.

-   Understand the difference between different **vector data types**.

-   Learn about the importance and how to **clean and process** geospatial data.

-   Learn about **interpolation** methods, why they are useful and when they should be used.

-   Explore the concept of spatial and temporal **stability of zones**, and how to incorporate them into a recommendation.

-   Learn about different **clustering analysis** for management zone creation.

-   Create zone-based **variable rate recommendation**.

-   Understand differences and value of spatial layers used in PA, including **yield monitor**, **soils**, and **satellite remote sensing** data.

::: callout-warning
All the objectives above will be explored in a hands-on approach through the use of the **R programming language** with students coding along live with the instructor.
:::

------------------------------------------------------------------------

# 2. Agenda and Topics `r icons::fontawesome("calendar-check")`

This is a tentative agenda.\
This can be changed/adapted to fit the speed that material is being covered.\
More details will be provided as the classes progress.

```{r echo=FALSE, message=F}
# Defining function
addlink <- function(link, type=1) {
  logo <- ifelse(type == 1, 'youtube', 'github')
  paste0("<a href=\"", link, "\">", as.character(fontawesome::fa(logo, width = "2em")), "</a>")
}

# Defining lecture combos (Wednesdays, 2 videos per class)
## 1
vc1 <- paste(
  addlink('https://tinyurl.com/2ebw3a2m', 1),
  "\\\n",
  addlink('https://tinyurl.com/4z7tp4en', 1))
cc1 <- paste(
  #addlink('https://tinyurl.com/43s2bbbp', 2),
  "\\\n",
  addlink('https://tinyurl.com/4jxw48hw', 2))

#2
vc2 <- paste0(
  addlink('https://youtu.be/8tiKO0wRkMs', 1),
  "\\\n",
  addlink('https://youtu.be/fOl3s6FfwuA', 1)
)

cc2 <- paste0(
  addlink('https://tinyurl.com/4jxw48hw', 2), 
  "\\\n",
  addlink('https://tinyurl.com/4jxw48hw', 2)
)

#3 
vc3 <- paste0(
  addlink('https://youtu.be/En57xMa3acM', 1),
  "\\\n",
  addlink('https://youtu.be/dGQA0AexPL4', 1)
)


cc3 <- paste0(
  #addlink('https://tinyurl.com/34uen9nw', 2), 
  #"\\\n",
  addlink('https://tinyurl.com/34uen9nw', 2)
)  

#4 
vc4 <- paste0(
  addlink('https://youtu.be/S9cebjDp9w0', 1),
  "\\\n",
  addlink('https://youtu.be/PhKEUW5PoLg', 1)
)


cc4 <- paste0(
  "\\\n",
  addlink('https://tinyurl.com/2mee6arp', 2)
)  

#5 
vc5 <- paste0(
  addlink('https://youtu.be/CNHEbq4DGP0', 1),
  "\\\n",
  addlink('https://youtu.be/TZh-bMrEtfg', 1)
)


cc5 <- paste0(
  "\\\n",
  addlink('https://tinyurl.com/22turreb', 2)
)  


library(dplyr, warn.conflicts = F)
agenda <- tribble(~Time, ~Activity, ~Video, ~`Partial Code`,
                  "Mon, Feb 07\\\n(9:10-10:00)",
                  "Website
                  \\\nR & RStudio intro pt.1",
                  addlink('https://tinyurl.com/58tmy923', 1),
                  addlink('https://tinyurl.com/43s2bbbp', 2),
                  
                  "Wed, Feb 09\\\n(9:10-11:10)",
                  "R & RStudio intro pt.2
                  \\\nRStudio projects
                  \\\nRmarkdown
                  \\\nAssignment #1 - Paper",
                  vc1,
                  cc1,
                  
                  
                  "Fri, Feb 11\\\n(9:10-10:00)", 
                  "(spatial) EDA",
                  addlink('https://youtu.be/BE8dqiS53SQ', 1),
                  "",
                  #addlink('https://tinyurl.com/4jxw48hw', 2),
                  
                  "Mon, Feb 14\\\n(9:10-10:00)", 
                  "Assignment #1 DUE
                  \\\nYield data wrangling",
                  addlink('https://youtu.be/0PikvQ_Eyqg', 1),
                  " ",
                  #addlink('https://tinyurl.com/4jxw48hw', 2),
                  
                  "Wed, Feb 16\\\n(9:10-11:10)", 
                  "Yield monitor data cleaning
                  \\\nAssignment #2 - Cleaning",
                  
                  vc2,
                  " ",
                  
                  "Fri, Feb 18\\\n(9:10-10:00)",
                  "Assignment #2 DUE
                  \\\nYield interpolation
                  \\\nGrid extraction",
                  addlink('https://youtu.be/beg7lD63OeI', 1),
                  addlink('https://tinyurl.com/52sa473j', 2),
                  
                  
                  "Fri, Mar 04\\\n(9:10-10:00)",
                  "Yield interpolation
                  \\\nGrid extraction
                  \\\nAssignment #3",
                  
                  addlink('https://youtu.be/xxcvFeVYe7Y', 1),
                  " ",
                  #addlink('https://tinyurl.com/52sa473j', 2),
                  
                  "Wed, Mar 16\\\n(9:10-11:10)",
                  "Assignment #3 DUE
                  \\\nYield spatial stability
                  \\\n Yield spatial-temporal stability",
                  vc3,
                  cc3,
                  
                  "Fri, Mar 25\\\n(9:10-10:00)",
                  "Terrain processing pt.1",
                  addlink('https://youtu.be/Whirsl3rSY8', 1),
                  addlink("https://tinyurl.com/3b468m8x",2),
                  
                  "Mon, Mar 28\\\n(9:10-10:00)",
                  "Terrain processing pt.2",
                  addlink("https://youtu.be/HBA32F3jS9k",1),
                  " ",
                  
                  "Wed, Mar 30\\\n(9:10-11:10)",
                  "Terrain processing pt.3
                  \\\nSoil ECa",
                  vc4,
                  cc4,
                  
                  "Fri, April 1\\\n(9:10-10:00)",
                  "Clustering for zone creation
                  \\\nDefining number of zones",
                  addlink("https://youtu.be/mXXHn9diipg",1),
                  addlink("https://tinyurl.com/2mrah8mf",2),
                  
                  "Fri, Apr 22\\\n(9:10-10:00)",
                  "Smoothing zones",
                  addlink("https://youtu.be/4g67DemrS6I",1),
                  " ",
                  
                  "Mon, Apr 25\\\n(9:10-10:00)",
                  "Validating zones with soils data",
                  addlink("https://youtu.be/R_kjvQkgNjM",1),
                  " ",
                  
                  
                  "Wed, Apr 27\\\n(9:10-11:10)",
                  "Validating zones with yield data
                  \\\nVariable rate N prescription",
                  vc5,
                  cc5,
                  
                  "Fri, Apr 29\\\n(9:10-10:00)",
                  "Validating zones with yield data
                  \\\nFinal project instructions",
                  addlink("https://youtu.be/yqzoM2uQGho",1),
                  " ",
                  
                  
                  
)

library(kableExtra)
library(formattable)
library(knitr)
library(gt)


agenda %>%
  gt() %>%
  fmt_markdown(columns = everything())

```

------------------------------------------------------------------------

# 3. Resources `r icons::fontawesome("question")`

If you need assistance, you can reach me at **lmbastos\@uga.edu**.

If you are in Athens, my office is at **4115B Miller Plant Sciences Hall**, feel free to drop by anytime.

After you start getting familiarized with R, here are some online resources:\
- [Geocomputation with R book](https://geocompr.robinlovelace.net/index.html)\
- [Introduction to Spatial Data Programming with R book](http://132.72.155.230:3838/r/index.html)\
- [`ggplot2` cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/data-visualization-2.1.pdf)\
- [`dplyr` data transformation cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/data-transformation.pdf)\
- [`tidyr` data tidying cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/tidyr.pdf)\
- [`sf` cheatsheet](https://github.com/rstudio/cheatsheets/blob/main/sf.pdf)\
- [Colorblind-friendly palettes in R](https://cran.r-project.org/web/packages/viridis/vignettes/intro-to-viridis.html)\
- [Violin/density plot vs. boxplots](https://blog.bioturing.com/2018/05/16/5-reasons-you-should-use-a-violin-graph/)\
- [File naming conventions](https://speakerdeck.com/jennybc/how-to-name-files?slide=1)\
- [Workflow maintenance](https://speakerdeck.com/jennybc/zen-and-the-art-of-workflow-maintenance)
